server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/neo_user_db
    username: postgres
    password: root
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yTmVvQmFua0pXVFRva2VuU2lnbmluZzEyMzQ1Njc4OTA=
  expiration: 86400000