spring:
  application:
    name: account-service

  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


  datasource:
    url: jdbc:postgresql://localhost:5432/neo_bank
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update